### ISSUE TITLE
How to save the model???

### ISSUE THREAD

**Issue by FSalazarV** [guillaume-chevalier/python-caffe-custom-cifar-10-conv-net#1]
Hello, how can i save the trained model for a later use and how to load it to classify an image??

**Comment by guillaume-chevalier** [comment]
I have already set up to save the model automatically. The weights are already committed and are in the file `cnn_snapshot_iter_100000.caffemodel`. 

If you want to save at different iterations while training, you can edit those lines in `cnn_solver_rms.prototxt`: 
```
snapshot: 25000
snapshot_prefix: "cnn_snapshot"
```
We see that here the snapshot is set at 25000, so I think normally it should have saved the weights 4 times, therefore I probably only committed the final ones. 

I did this project 1 year and a half ago and I think it is a bit old. Last week, I rebuilt this project, but on the CIFAR-100 dataset rather than CIFAR-10, and with Keras and Hyperopt: 
https://github.com/guillaume-chevalier/Hyperopt-Keras-CNN-CIFAR-100
